(define (sum-of-two-largest x y z)
  (define (sum-of-squares x y) (+ (* x x) (* y y)))
  (if (> x y)
      (if (> y z)
          (sum-of-squares x y)
          (sum-of-squares x z)
          )
      (if (> x z)
          (sum-of-squares x y)
          (sum-of-squares y z)
          )
      )
  )

(sum-of-two-largest 1 2 3)